/**
 * Built-in Themes for Shardwright (Cannot be deleted)
 *
 * Kept in a separate file so [`ui/modals/themes-modal.js`](ui/modals/themes-modal.js) stays focused on UI logic.
 */

export const BUILTIN_THEMES = {
    default: {
    id: 'default',
    name: 'Default',
    description: 'Inherits SillyTavern\'s current theme - no custom styling',
    preview: '🎭',
    builtin: true,
    colors: {
        // Primary colors - inherit from ST's accent/emphasis
        '--shardwright-primary': 'var(--SmartThemeEmColor, inherit)',
        '--shardwright-primary-hover': 'var(--SmartThemeEmColor, inherit)',
        '--shardwright-primary-active': 'var(--SmartThemeEmColor, inherit)',

        // Backgrounds - use ST's blur tint colors
        '--shardwright-bg-primary': 'var(--SmartThemeBlurTintColor)',
        '--shardwright-bg-secondary': 'var(--SmartThemeChatMesColorStyle, transparent)',
        '--shardwright-bg-tertiary': 'var(--SmartThemeChatMesColorStyle, transparent)',
        '--shardwright-bg-input': 'var(--SmartThemeBlurTintColor)',

        // Text - inherit ST's body color
        '--shardwright-text-primary': 'var(--SmartThemeBodyColor)',
        '--shardwright-text-secondary': 'var(--SmartThemeBodyColor)',
        '--shardwright-text-muted': 'var(--SmartThemeBodyColor)',

        // Borders
        '--shardwright-border': 'var(--SmartThemeBorderColor, transparent)',
        '--shardwright-border-focus': 'var(--SmartThemeEmColor, inherit)',

        // Status colors - keep functional defaults
        '--shardwright-success': '#4caf50',
        '--shardwright-warning': '#ff9800',
        '--shardwright-error': '#f44336',
        '--shardwright-info': 'var(--SmartThemeEmColor, #2196f3)',

        // Weight colors - keep for functionality
        '--shardwright-weight-critical': '#ff4444',
        '--shardwright-weight-major': '#ff8c00',
        '--shardwright-weight-moderate': '#ffd700',
        '--shardwright-weight-minor': '#90ee90',
        '--shardwright-weight-trivial': 'var(--SmartThemeBodyColor)',

        // Accents
        '--shardwright-nsfw-accent': '#ff6b9d',
        '--shardwright-highlight': 'transparent',
        '--shardwright-quote': 'var(--SmartThemeQuoteColor, inherit)',

        // Shadows - use ST's shadow color as the shadow pigment
        '--shardwright-shadow': '0 4px 10px var(--SmartThemeShadowColor, rgba(0, 0, 0, 0.35))',
        '--shardwright-shadow-lg': '0 10px 25px var(--SmartThemeShadowColor, rgba(0, 0, 0, 0.45))',

        // Transitions
        '--shardwright-transition': '0.2s ease',

        // Misc
        '--shardwright-text-hint': 'var(--SmartThemeBodyColor)',
        '--shardwright-rescue-bg': 'var(--SmartThemeBlurTintColor)',
        '--shardwright-rescue-bg-hover': 'var(--SmartThemeBlurTintColor)',
        '--shardwright-stop-hover': '#c0392b',
        '--shardwright-overlay-bg': 'var(--SmartThemeBlurTintColor)',
        '--shardwright-focus-glow': 'transparent',
    }
},
    fantasyRpg: {
        "id": "fantasyrpg",
        "name": "Gilded Codex",
        "description": "Ancient tomes bound in dragon leather, illuminated by flickering torchlight and gilded manuscript edges",
        "preview": "⚔️",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(218, 165, 32, 1)",
          "--shardwright-primary-hover": "rgba(241, 200, 80, 1)",
          "--shardwright-primary-active": "rgba(170, 130, 20, 1)",
          "--shardwright-bg-primary": "rgba(22, 14, 8, 0.98)",
          "--shardwright-bg-secondary": "rgba(38, 25, 14, 0.96)",
          "--shardwright-bg-tertiary": "rgba(55, 38, 22, 0.92)",
          "--shardwright-bg-input": "rgba(16, 10, 5, 0.85)",
          "--shardwright-text-primary": "rgba(245, 232, 199, 1)",
          "--shardwright-text-secondary": "rgba(210, 180, 120, 1)",
          "--shardwright-text-muted": "rgba(180, 150, 95, 0.7)",
          "--shardwright-text-hint": "rgba(130, 105, 70, 0.8)",
          "--shardwright-border": "rgba(180, 145, 50, 0.3)",
          "--shardwright-border-focus": "rgba(139, 69, 19, 0.9)",
          "--shardwright-success": "rgba(46, 139, 87, 1)",
          "--shardwright-warning": "rgba(205, 155, 29, 1)",
          "--shardwright-error": "rgba(148, 20, 20, 1)",
          "--shardwright-info": "rgba(80, 120, 165, 1)",
          "--shardwright-weight-critical": "rgba(148, 20, 20, 1)",
          "--shardwright-weight-major": "rgba(178, 85, 20, 1)",
          "--shardwright-weight-moderate": "rgba(205, 155, 29, 1)",
          "--shardwright-weight-minor": "rgba(46, 139, 87, 1)",
          "--shardwright-weight-trivial": "rgba(130, 105, 70, 0.8)",
          "--shardwright-nsfw-accent": "rgba(120, 35, 50, 1)",
          "--shardwright-highlight": "rgba(218, 165, 32, 0.1)",
          "--shardwright-quote": "rgba(195, 160, 45, 1)",
          "--shardwright-shadow": "0 3px 10px rgba(0, 0, 0, 0.6), 0 0 20px rgba(218, 165, 32, 0.08)",
          "--shardwright-shadow-lg": "0 6px 28px rgba(0, 0, 0, 0.7), 0 0 50px rgba(218, 165, 32, 0.12)",
          "--shardwright-overlay-bg": "rgba(12, 8, 4, 0.88)",
          "--shardwright-focus-glow": "rgba(218, 165, 32, 0.2)",
          "--shardwright-transition": "0.25s ease-out",
          "--shardwright-rescue-bg": "rgba(85, 55, 25, 0.9)",
          "--shardwright-rescue-bg-hover": "rgba(100, 65, 30, 0.95)",
          "--shardwright-stop-hover": "rgba(100, 15, 15, 0.9)",
          "--shardwright-font-primary": "Palatino Linotype, Palatino, Book Antiqua, serif",
          "--shardwright-font-secondary": "Palatino Linotype, Palatino, Book Antiqua, serif",
          "--shardwright-font-muted": "Palatino Linotype, Palatino, Book Antiqua, serif",
          "--shardwright-font-hint": "Palatino Linotype, Palatino, Book Antiqua, serif"
        },
        "extraStyles": ""      
    },
    midas: {
        "id": "midas",
        "name": "Midas Vault",
        "description": "Everything touched turns to burnished gold against an abyss of pure black — opulence distilled to its essence",
        "preview": "👑",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(212, 175, 55, 1)",
          "--shardwright-primary-hover": "rgba(247, 231, 206, 1)",
          "--shardwright-primary-active": "rgba(165, 135, 40, 1)",
          "--shardwright-bg-primary": "rgba(6, 6, 6, 1)",
          "--shardwright-bg-secondary": "rgba(16, 14, 12, 1)",
          "--shardwright-bg-tertiary": "rgba(26, 23, 19, 1)",
          "--shardwright-bg-input": "rgba(0, 0, 0, 1)",
          "--shardwright-text-primary": "rgba(247, 231, 206, 1)",
          "--shardwright-text-secondary": "rgba(212, 175, 55, 1)",
          "--shardwright-text-muted": "rgba(160, 140, 95, 0.75)",
          "--shardwright-text-hint": "rgba(100, 88, 62, 0.8)",
          "--shardwright-border": "rgba(212, 175, 55, 0.35)",
          "--shardwright-border-focus": "rgba(247, 231, 206, 0.9)",
          "--shardwright-success": "rgba(39, 174, 96, 1)",
          "--shardwright-warning": "rgba(243, 156, 18, 1)",
          "--shardwright-error": "rgba(192, 57, 43, 1)",
          "--shardwright-info": "rgba(212, 175, 55, 1)",
          "--shardwright-weight-critical": "rgba(192, 57, 43, 1)",
          "--shardwright-weight-major": "rgba(211, 84, 0, 1)",
          "--shardwright-weight-moderate": "rgba(243, 156, 18, 1)",
          "--shardwright-weight-minor": "rgba(39, 174, 96, 1)",
          "--shardwright-weight-trivial": "rgba(100, 88, 62, 0.8)",
          "--shardwright-nsfw-accent": "rgba(192, 57, 43, 1)",
          "--shardwright-highlight": "rgba(212, 175, 55, 0.1)",
          "--shardwright-quote": "rgba(247, 231, 206, 1)",
          "--shardwright-shadow": "0 1px 6px rgba(0, 0, 0, 0.9), 0 0 18px rgba(212, 175, 55, 0.1)",
          "--shardwright-shadow-lg": "0 4px 24px rgba(0, 0, 0, 0.95), 0 0 40px rgba(212, 175, 55, 0.18)",
          "--shardwright-overlay-bg": "rgba(0, 0, 0, 0.92)",
          "--shardwright-focus-glow": "rgba(212, 175, 55, 0.35)",
          "--shardwright-transition": "0.3s cubic-bezier(0.25, 0.8, 0.25, 1)",
          "--shardwright-rescue-bg": "rgba(40, 35, 22, 0.95)",
          "--shardwright-rescue-bg-hover": "rgba(55, 48, 28, 1)",
          "--shardwright-stop-hover": "rgba(130, 15, 15, 0.9)",
          "--shardwright-font-primary": "Didot, Bodoni MT, Noto Serif Display, serif",
          "--shardwright-font-secondary": "Didot, Bodoni MT, Noto Serif Display, serif",
          "--shardwright-font-muted": "Didot, Bodoni MT, Noto Serif Display, serif",
          "--shardwright-font-hint": "Didot, Bodoni MT, Noto Serif Display, serif"
        },
        "extraStyles": ""
      },
    asteroid: {
        "id": "asteroiddiner",
        "name": "Asteroid Diner",
        "description": "Neon-buzzing jukebox, chrome counter stools, and coffee brewed in zero-G — order up at the edge of the cosmos",
        "preview": "🛸",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(252, 163, 17, 1)",
          "--shardwright-primary-hover": "rgba(255, 190, 70, 1)",
          "--shardwright-primary-active": "rgba(215, 138, 0, 1)",
          "--shardwright-bg-primary": "rgba(8, 8, 14, 0.98)",
          "--shardwright-bg-secondary": "rgba(16, 16, 24, 0.96)",
          "--shardwright-bg-tertiary": "rgba(26, 26, 38, 0.92)",
          "--shardwright-bg-input": "rgba(5, 5, 10, 0.85)",
          "--shardwright-text-primary": "rgba(240, 240, 245, 1)",
          "--shardwright-text-secondary": "rgba(252, 163, 17, 1)",
          "--shardwright-text-muted": "rgba(200, 195, 185, 0.6)",
          "--shardwright-text-hint": "rgba(150, 148, 160, 0.75)",
          "--shardwright-border": "rgba(252, 163, 17, 0.28)",
          "--shardwright-border-focus": "rgba(0, 180, 216, 0.85)",
          "--shardwright-success": "rgba(45, 198, 83, 1)",
          "--shardwright-warning": "rgba(255, 209, 102, 1)",
          "--shardwright-error": "rgba(230, 57, 70, 1)",
          "--shardwright-info": "rgba(0, 180, 216, 1)",
          "--shardwright-weight-critical": "rgba(230, 57, 70, 1)",
          "--shardwright-weight-major": "rgba(252, 163, 17, 1)",
          "--shardwright-weight-moderate": "rgba(255, 209, 102, 1)",
          "--shardwright-weight-minor": "rgba(45, 198, 83, 1)",
          "--shardwright-weight-trivial": "rgba(150, 148, 160, 0.75)",
          "--shardwright-nsfw-accent": "rgba(157, 78, 221, 1)",
          "--shardwright-highlight": "rgba(252, 163, 17, 0.09)",
          "--shardwright-quote": "rgba(255, 209, 102, 1)",
          "--shardwright-shadow": "0 2px 10px rgba(0, 0, 0, 0.6), 0 0 14px rgba(252, 163, 17, 0.08)",
          "--shardwright-shadow-lg": "0 6px 24px rgba(0, 0, 0, 0.7), 0 0 45px rgba(252, 163, 17, 0.12)",
          "--shardwright-overlay-bg": "rgba(4, 4, 8, 0.88)",
          "--shardwright-focus-glow": "rgba(0, 180, 216, 0.22)",
          "--shardwright-transition": "0.2s ease-out",
          "--shardwright-rescue-bg": "rgba(42, 40, 55, 0.9)",
          "--shardwright-rescue-bg-hover": "rgba(55, 52, 70, 0.95)",
          "--shardwright-stop-hover": "rgba(100, 12, 12, 0.9)",
          "--shardwright-font-primary": "Space Grotesk, Michroma, Exo 2, sans-serif",
          "--shardwright-font-secondary": "Space Grotesk, Michroma, Exo 2, sans-serif",
          "--shardwright-font-muted": "Space Mono, Fira Code, monospace",
          "--shardwright-font-hint": "Space Mono, Fira Code, monospace"
        },
        "extraStyles": ""
      },
    fungalmycelium: {
        "id": "fungalmycelium-reworked",
        "name": "Fungal Mycelium",
        "description": "Bioluminescent spore networks pulsing through damp forest undergrowth — the intelligence beneath the soil",
        "preview": "🍄",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(180, 235, 0, 1)",
          "--shardwright-primary-hover": "rgba(205, 255, 55, 1)",
          "--shardwright-primary-active": "rgba(140, 190, 0, 1)",
          "--shardwright-bg-primary": "rgba(12, 10, 6, 0.98)",
          "--shardwright-bg-secondary": "rgba(24, 20, 10, 0.96)",
          "--shardwright-bg-tertiary": "rgba(38, 32, 16, 0.92)",
          "--shardwright-bg-input": "rgba(8, 6, 3, 0.85)",
          "--shardwright-text-primary": "rgba(225, 240, 195, 1)",
          "--shardwright-text-secondary": "rgba(180, 235, 0, 1)",
          "--shardwright-text-muted": "rgba(155, 195, 60, 0.55)",
          "--shardwright-text-hint": "rgba(120, 150, 55, 0.7)",
          "--shardwright-border": "rgba(180, 235, 0, 0.22)",
          "--shardwright-border-focus": "rgba(85, 139, 47, 0.85)",
          "--shardwright-success": "rgba(118, 255, 3, 1)",
          "--shardwright-warning": "rgba(255, 171, 0, 1)",
          "--shardwright-error": "rgba(213, 0, 0, 1)",
          "--shardwright-info": "rgba(100, 221, 23, 1)",
          "--shardwright-weight-critical": "rgba(213, 0, 0, 1)",
          "--shardwright-weight-major": "rgba(255, 140, 0, 1)",
          "--shardwright-weight-moderate": "rgba(255, 171, 0, 1)",
          "--shardwright-weight-minor": "rgba(118, 255, 3, 1)",
          "--shardwright-weight-trivial": "rgba(120, 150, 55, 0.7)",
          "--shardwright-nsfw-accent": "rgba(106, 27, 154, 1)",
          "--shardwright-highlight": "rgba(180, 235, 0, 0.07)",
          "--shardwright-quote": "rgba(174, 234, 0, 1)",
          "--shardwright-shadow": "0 2px 10px rgba(0, 0, 0, 0.6), 0 0 22px rgba(180, 235, 0, 0.06)",
          "--shardwright-shadow-lg": "0 6px 26px rgba(0, 0, 0, 0.7), 0 0 55px rgba(180, 235, 0, 0.1)",
          "--shardwright-overlay-bg": "rgba(6, 5, 2, 0.9)",
          "--shardwright-focus-glow": "rgba(180, 235, 0, 0.18)",
          "--shardwright-transition": "0.3s ease-out",
          "--shardwright-rescue-bg": "rgba(50, 75, 20, 0.85)",
          "--shardwright-rescue-bg-hover": "rgba(62, 90, 28, 0.92)",
          "--shardwright-stop-hover": "rgba(120, 10, 10, 0.9)",
          "--shardwright-font-primary": "Nunito, Quicksand, sans-serif",
          "--shardwright-font-secondary": "Nunito, Quicksand, sans-serif",
          "--shardwright-font-muted": "Nunito, Quicksand, sans-serif",
          "--shardwright-font-hint": "Nunito, Quicksand, sans-serif"
        },
        "extraStyles": ""
      },
    vampirenoir: {
        "id": "vampirenoir-reworked",
        "name": "Vampire Noir",
        "description": "Candlelit chambers draped in crimson velvet — the aristocratic undead survey their domain through antique mirrors",
        "preview": "🧛",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(175, 45, 35, 1)",
          "--shardwright-primary-hover": "rgba(210, 60, 50, 1)",
          "--shardwright-primary-active": "rgba(140, 32, 28, 1)",
          "--shardwright-bg-primary": "rgba(12, 8, 10, 0.98)",
          "--shardwright-bg-secondary": "rgba(22, 13, 16, 0.96)",
          "--shardwright-bg-tertiary": "rgba(32, 18, 22, 0.92)",
          "--shardwright-bg-input": "rgba(8, 4, 6, 0.85)",
          "--shardwright-text-primary": "rgba(235, 230, 225, 1)",
          "--shardwright-text-secondary": "rgba(195, 165, 110, 1)",
          "--shardwright-text-muted": "rgba(165, 140, 100, 0.6)",
          "--shardwright-text-hint": "rgba(120, 105, 90, 0.7)",
          "--shardwright-border": "rgba(175, 45, 35, 0.3)",
          "--shardwright-border-focus": "rgba(195, 165, 110, 0.85)",
          "--shardwright-success": "rgba(39, 174, 96, 1)",
          "--shardwright-warning": "rgba(200, 80, 10, 1)",
          "--shardwright-error": "rgba(140, 30, 25, 1)",
          "--shardwright-info": "rgba(84, 153, 199, 1)",
          "--shardwright-weight-critical": "rgba(175, 45, 35, 1)",
          "--shardwright-weight-major": "rgba(200, 80, 10, 1)",
          "--shardwright-weight-moderate": "rgba(195, 165, 110, 1)",
          "--shardwright-weight-minor": "rgba(39, 174, 96, 1)",
          "--shardwright-weight-trivial": "rgba(120, 105, 90, 0.7)",
          "--shardwright-nsfw-accent": "rgba(155, 89, 182, 1)",
          "--shardwright-highlight": "rgba(175, 45, 35, 0.08)",
          "--shardwright-quote": "rgba(212, 172, 13, 1)",
          "--shardwright-shadow": "0 3px 10px rgba(0, 0, 0, 0.75), 0 0 12px rgba(175, 45, 35, 0.12)",
          "--shardwright-shadow-lg": "0 6px 22px rgba(0, 0, 0, 0.85), 0 0 38px rgba(175, 45, 35, 0.18)",
          "--shardwright-overlay-bg": "rgba(8, 3, 4, 0.92)",
          "--shardwright-focus-glow": "rgba(175, 45, 35, 0.2)",
          "--shardwright-transition": "0.25s ease",
          "--shardwright-rescue-bg": "rgba(65, 28, 28, 0.9)",
          "--shardwright-rescue-bg-hover": "rgba(80, 35, 35, 0.95)",
          "--shardwright-stop-hover": "rgba(85, 8, 8, 0.9)",
          "--shardwright-font-primary": "Crimson Text, Cormorant Garamond, Georgia, serif",
          "--shardwright-font-secondary": "Crimson Text, Cormorant Garamond, Georgia, serif",
          "--shardwright-font-muted": "Crimson Text, Cormorant Garamond, Georgia, serif",
          "--shardwright-font-hint": "Crimson Text, Cormorant Garamond, Georgia, serif"
        },
        "extraStyles": ""
      },
    neoncyber: {
        "id": "neoncyberpunk-reworked",
        "name": "Neon Cyberpunk",
        "description": "Rain-slicked megacity streets reflecting holographic billboards — jack in, tune out, burn chrome",
        "preview": "🤖",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(0, 255, 245, 1)",
          "--shardwright-primary-hover": "rgba(60, 255, 250, 1)",
          "--shardwright-primary-active": "rgba(0, 200, 195, 1)",
          "--shardwright-bg-primary": "rgba(6, 6, 18, 0.98)",
          "--shardwright-bg-secondary": "rgba(14, 14, 32, 0.96)",
          "--shardwright-bg-tertiary": "rgba(24, 24, 48, 0.92)",
          "--shardwright-bg-input": "rgba(3, 3, 12, 0.85)",
          "--shardwright-text-primary": "rgba(220, 220, 255, 1)",
          "--shardwright-text-secondary": "rgba(255, 0, 255, 1)",
          "--shardwright-text-muted": "rgba(180, 140, 255, 0.55)",
          "--shardwright-text-hint": "rgba(100, 100, 155, 0.75)",
          "--shardwright-border": "rgba(0, 255, 245, 0.3)",
          "--shardwright-border-focus": "rgba(255, 0, 255, 0.85)",
          "--shardwright-success": "rgba(0, 255, 157, 1)",
          "--shardwright-warning": "rgba(255, 240, 0, 1)",
          "--shardwright-error": "rgba(255, 0, 60, 1)",
          "--shardwright-info": "rgba(0, 184, 255, 1)",
          "--shardwright-weight-critical": "rgba(255, 0, 60, 1)",
          "--shardwright-weight-major": "rgba(255, 100, 0, 1)",
          "--shardwright-weight-moderate": "rgba(255, 240, 0, 1)",
          "--shardwright-weight-minor": "rgba(0, 255, 157, 1)",
          "--shardwright-weight-trivial": "rgba(100, 100, 155, 0.75)",
          "--shardwright-nsfw-accent": "rgba(255, 0, 144, 1)",
          "--shardwright-highlight": "rgba(0, 255, 245, 0.07)",
          "--shardwright-quote": "rgba(255, 50, 50, 1)",
          "--shardwright-shadow": "0 0 12px rgba(0, 255, 245, 0.2), 0 0 24px rgba(255, 0, 255, 0.12)",
          "--shardwright-shadow-lg": "0 0 24px rgba(0, 255, 245, 0.3), 0 0 50px rgba(255, 0, 255, 0.2)",
          "--shardwright-overlay-bg": "rgba(3, 3, 8, 0.92)",
          "--shardwright-focus-glow": "rgba(0, 255, 245, 0.25)",
          "--shardwright-transition": "0.15s ease-out",
          "--shardwright-rescue-bg": "rgba(30, 28, 60, 0.9)",
          "--shardwright-rescue-bg-hover": "rgba(42, 40, 75, 0.95)",
          "--shardwright-stop-hover": "rgba(70, 0, 15, 0.9)",
          "--shardwright-font-primary": "Share Tech Mono, Fira Code, Consolas, monospace",
          "--shardwright-font-secondary": "Share Tech Mono, Fira Code, Consolas, monospace",
          "--shardwright-font-muted": "Share Tech Mono, Fira Code, Consolas, monospace",
          "--shardwright-font-hint": "Share Tech Mono, Fira Code, Consolas, monospace"
        },
        "extraStyles": ""
      },
    obsidianshard: {
        "id": "obsidianshard-reworked",
        "name": "Obsidian Shard",
        "description": "Volcanic glass fractured into impossible geometries — pure darkness with razor-thin white edges catching cold light",
        "preview": "🖤",
        "builtin": false,
        "colors": {
          "--shardwright-primary": "rgba(245, 245, 245, 1)",
          "--shardwright-primary-hover": "rgba(255, 255, 255, 1)",
          "--shardwright-primary-active": "rgba(210, 210, 210, 1)",
          "--shardwright-bg-primary": "rgba(3, 3, 3, 0.99)",
          "--shardwright-bg-secondary": "rgba(10, 10, 10, 0.97)",
          "--shardwright-bg-tertiary": "rgba(18, 18, 18, 0.94)",
          "--shardwright-bg-input": "rgba(0, 0, 0, 0.95)",
          "--shardwright-text-primary": "rgba(255, 255, 255, 1)",
          "--shardwright-text-secondary": "rgba(155, 155, 155, 1)",
          "--shardwright-text-muted": "rgba(110, 110, 110, 0.7)",
          "--shardwright-text-hint": "rgba(65, 65, 65, 0.8)",
          "--shardwright-border": "rgba(255, 255, 255, 0.15)",
          "--shardwright-border-focus": "rgba(255, 255, 255, 0.9)",
          "--shardwright-success": "rgba(0, 230, 118, 1)",
          "--shardwright-warning": "rgba(255, 214, 0, 1)",
          "--shardwright-error": "rgba(255, 23, 68, 1)",
          "--shardwright-info": "rgba(41, 121, 255, 1)",
          "--shardwright-weight-critical": "rgba(255, 23, 68, 1)",
          "--shardwright-weight-major": "rgba(255, 140, 0, 1)",
          "--shardwright-weight-moderate": "rgba(255, 214, 0, 1)",
          "--shardwright-weight-minor": "rgba(0, 230, 118, 1)",
          "--shardwright-weight-trivial": "rgba(65, 65, 65, 0.8)",
          "--shardwright-nsfw-accent": "rgba(255, 64, 129, 1)",
          "--shardwright-highlight": "rgba(255, 255, 255, 0.05)",
          "--shardwright-quote": "rgba(189, 189, 189, 1)",
          "--shardwright-shadow": "0 2px 8px rgba(0, 0, 0, 1), 0 1px 3px rgba(0, 0, 0, 1)",
          "--shardwright-shadow-lg": "0 6px 20px rgba(0, 0, 0, 1), 0 2px 8px rgba(0, 0, 0, 1)",
          "--shardwright-overlay-bg": "rgba(0, 0, 0, 0.98)",
          "--shardwright-focus-glow": "rgba(255, 255, 255, 0.08)",
          "--shardwright-transition": "0.1s ease",
          "--shardwright-rescue-bg": "rgba(20, 20, 20, 0.95)",
          "--shardwright-rescue-bg-hover": "rgba(30, 30, 30, 1)",
          "--shardwright-stop-hover": "rgba(50, 0, 0, 0.95)",
          "--shardwright-font-primary": "Inter, Helvetica Neue, Arial, sans-serif",
          "--shardwright-font-secondary": "Inter, Helvetica Neue, Arial, sans-serif",
          "--shardwright-font-muted": "Inter, Helvetica Neue, Arial, sans-serif",
          "--shardwright-font-hint": "JetBrains Mono, Fira Code, monospace"
        },
        "extraStyles": ""
      },
    
};
