import assert from 'node:assert/strict'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path'; import test from 'node:test';
import { getStoragePaths } from './core.js'; import { reconcileTranscriptMessages, TranscriptMessageResolution } from './transcript-message-reconciliation.js';
function paths(){return getStoragePaths(fs.mkdtempSync(path.join(os.tmpdir(),'shardwright-reconcile-')));}
function write(target,batches){fs.mkdirSync(target.storageRoot,{recursive:true});fs.writeFileSync(target.transcriptMessageLedgerPath,batches.map((batch,index)=>JSON.stringify({ledgerVersion:1,sequence:index+1,batchHash:'bad',batch})).join('\n'));}
// Ledger validation intentionally requires an exact hash, so use the real writer's canonical hash through a minimal valid fixture construction.
import crypto from 'node:crypto'; import { stableStringify } from './core.js';
function valid(target,batches){fs.mkdirSync(target.storageRoot,{recursive:true});fs.writeFileSync(target.transcriptMessageLedgerPath,batches.map((batch,index)=>JSON.stringify({ledgerVersion:1,sequence:index+1,batchHash:`sha256:${crypto.createHash('sha256').update(stableStringify(batch)).digest('hex')}`,batch})).join('\n'));}
function row(source,revision,order,native){return {messageRecordId:`${source}:${revision}:${order}`,sourceLogicalId:source,sourceRevisionHash:revision,sourceLocalOrder:order,nativeMessageId:native,completeContent:'x'};}
test('connects native IDs only within one source and keeps no-ID rows unresolved',()=>{const p=paths();valid(p,[{sourceLogicalId:'a',sourceRevisionHash:'r1',rows:[row('a','r1',0,'7'),row('a','r1',1,null)]},{sourceLogicalId:'a',sourceRevisionHash:'r2',rows:[row('a','r2',0,'7')]},{sourceLogicalId:'b',sourceRevisionHash:'r3',rows:[row('b','r3',0,'7')]}]);const r=reconcileTranscriptMessages(p);assert.equal(r.resolved.length,2);assert.equal(r.resolved[0].revisions.length,2);assert.equal(r.resolved[0].resolution,TranscriptMessageResolution.NATIVE_ID);assert.equal(r.unresolved.length,1);assert.equal(r.unresolved[0].resolution,TranscriptMessageResolution.UNRESOLVED);});
